# SPDX-FileCopyrightText: 2023 Firebot Gambling Script Contributors
#
# SPDX-License-Identifier: CC0-1.0

status = [
    "build", "style"
]
delete_merged_branches = true
use_squash_merge = true
cut_body_after = ""
