pull_request_rules:
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=build
      - check-success=style
      - title~=^build\(deps-dev\)[:] bump [^\s]+ from ([\d]+)\..+ to \1\.
    actions:
      merge:
        method: squash
