name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Use Node.js ${{ env.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.node }}
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-
    - name: Install Dependencies
      run: yarn install
    - name: Build
      run: yarn build
    - name: Install zip
      run: |
        apt-get update
        apt-get -y install zip
    - name: Create Release Zip
      run: |
        cp README.md dist/
        cp CHANGELOG.md dist/
        cp LICENSE dist/
        mv dist gambling-script
        md5sum gambling-script/*
        zip -r gambling-script-${{ env.RELEASE_VERSION }}.zip gambling-script
    - name: Release
      uses: softprops/action-gh-release@v0.1.5
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: gambling-script-${{ env.RELEASE_VERSION }}.zip
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
