name: Test

on:
  push:
    branches:
    - main
  pull_request:

env:
  CI: true
  node: 15.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.node }}
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-
    - name: Install Dependencies
      run: yarn install
    - name: TypeScript Test With Typechecking
      run: yarn test --ci
    - name: Annotate Client Test Results
      uses: ashley-taylor/junit-report-annotations-action@9ac2f823854c677f30e062dfe779445e33e5d380
      if: always()
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        path: junit.xml
        numFailures: 99
        
  style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.node }}
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-
    - name: Install Dependencies
      run: yarn install
    - name: TypeScript Formatting
      run: yarn prettier:check
    - name: TypeScript Code Style
      run: yarn lint
      if: success() || failure()
