name: Test

on:
  push:
    branches: [main, staging, trying]
  pull_request:
    branches: [main]

env:
  CI: true
  node: 14.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.node }}
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-
    - name: Install Dependencies
      run: yarn install
    - name: TypeScript Test
      run: yarn test:coverage --ci
    - name: Annotate Client Test Results
      uses: mikepenz/action-junit-report@v2.7.0
      if: always()
      with:
        report_paths: 'junit.xml'

  style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.node }}
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-
    - name: Install Dependencies
      run: yarn install
    - name: TypeScript Formatting
      run: yarn prettier:check
    - name: TypeScript Code Style
      run: yarn lint
      if: success() || failure()
